DjangoProject/urls.py
import os

from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog
import userprofile
from DjangoProject.settings import BASE_DIR
from blog.views import index, main,test

# from blog.views import main

urlpatterns = [

    path('admin/', admin.site.urls),
    path('index/',index),
    path('main/',main),
    url(r'^$', blog.views.home, name='home'),
    path('test/<str:a>/',blog.views.test,name='test'),
    path('test/<int:a>/',blog.views.test,name='test'),
    path('article/',blog.views.home,name='home'),
    path('',blog.views.articleList,name='articleList'),
    path('article/articleList/',blog.views.articleList,name='articleList'),
    path('article/article-detail/<int:id>/',blog.views.article_detail,name='article_detail'),

    path('article-create/',blog.views.article_create,name='article_create'),
    path('article/article-delete/<int:id>/',blog.views.article_delete,name='article_delete'),
    path('article/article-update/<int:id>/',blog.views.article_update,name='article_update'),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),

    path('comment/', include('comment.urls', namespace='comment')),

    # path('login/',userprofile.views.user_login,name='userLogin'),



]
# 用户头像相关
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
# /comment/urls.py

from django.urls import path

import userprofile
from . import views

app_name = 'userprofile'

urlpatterns = [

    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

userprofile/urls.py
# /userprofile/urls.py

from django.urls import path

import userprofile
from . import views

app_name = 'userprofile'

urlpatterns = [

path('login/', views.user_login, name='login'),
path('logout/', views.user_logout, name='logout'),
path('register',views.user_register,name='register'),
path('user-delete/<int:id>',views.user_delete,name='delete'),
path('edit/<int:id>/', views.profile_edit, name='edit'),


# path('index/',index),

]

templates/article/articleList.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/article/articleList/?order=normal">
                        最新
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="/article/articleList/?order=total_views">
                        最热
                    </a>
                </li>
            </ol>
    </nav>
                <div class="col-4 mr-4">
                    <form class="form-inline" >
                        <label class="sr-only">content</label>
                        <input type="text"
                            class="form-control mb-2 mr-sm-2"
                            name="search"
                            placeholder="搜索文章..."
                            required
                        >
                    </form>
                </div>
{% if search %}
        {% if articles %}
            <h4><span style="color: green">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
            <hr>
        {% endif %}
{% endif %}
    <div class="row mt-2">

        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="card col-11 mb-n1 hvr-glow mt-3">
        <!-- 卡片容器 -->
            <div class="row  align-items-center mt-2">
{#                <div class="col-5">#}
                    {% if article.avatar %}
                        <div class="col-3">
                            <img src="{{ article.avatar.url }}"
                                 alt="avatar"
                                 style="max-width:100%; border-radius: 20px"
                            >
                        </div>
                    {% endif %}
{#                </div>#}
                <div class=" h-90 " >



                    <!-- 标题 -->
                    <h3>
                        <b>
                            <a href="/article/article-detail/{{ article.id }}" style="color:black">{{ article.title }}</a>
                        </b>
                    </h3>
                    <!-- 摘要 -->
    {#                <div class="card-body">#}
                    <h5>
                        <p class="card-text" style="color:gray">{{ article.body|slice:'30' }}...</p>
    {#                </div>#}
                    </h5>

                    <!-- 注脚 -->
    {#                <div class="card-footer">#}




                    <div>
                            {% if article.column %}
                                <a href="?column={{ article.column.id }} " role="button" class="
                                        btn
                                        btn-sm
                                        hvr-pop
                                        btn-outline-success

                                        ">
                                {{ article.column.title }}
                                </a>
    {#                            <button href="/?column={{ article.column.title }}" type="button" style="height:30px;width:80px"#}
    {#                                class="btn btn-sm mb-2#}
    {#                                    {% if article.column.title == 'Android' %}#}
    {#                                        btn-success#}
    {#                                    {% elif article.column.title == 'JAVA' %}#}
    {#                                        btn-danger#}
    {#                                    {% elif article.column.title == 'Python' %}#}
    {#                                        btn-warning#}
    {#                                    {% endif %}#}
    {#                                "#}
    {#                            >#}
    {#                                {{ article.column.title }}#}
    {#                            </button>#}
                            {% endif %}
                            {% if article.tags %}
                                <span>

                                {% for tag in article.tags.all %}
                                     <a href="?tag={{ tag }}"
                                       class="badge badge-secondary">
                                        {{ tag }}
                                     </a>
                                {% endfor %}

                                </span>

                            {% endif %}
                    </div>
                    <b>
                        <p>
                            <span style="color: red;">
                                {{ article.total_views }} 浏览&nbsp;&nbsp;&nbsp;
                            </span>
                            <span style="color: green;">
                                {{ article.created | date:'Y-m-d'}} 创建&nbsp;&nbsp;&nbsp;
                            </span>
                            <span style="color: yellowgreen;">
                                {{ article.updated | date:'Y-m-d'}} 更新&nbsp;&nbsp;&nbsp;
                            </span>

                        </p>
                    </b>


    {#                    <a href=/article/article-detail/{{ article.id }} class="btn btn-primary">阅读本文</a>#}


    {#                </div>#}
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% if articles %}
<div class="pagination row">
    <div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}"
                   class="btn btn-secondary"
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}"
                   class="btn btn-secondary"
                >
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}"
                   class="btn btn-success"
                >
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
    </div>
</div>
{% else %}
{% endif %}
{% endblock content %}

templates/article/createpage.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
新建文章
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
{#            {% if method == "POST" %}#}
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>

                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!--column-->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control"
                            id="column"
                            name="column"
                    >
                            <option value="none">请选择栏目..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}" {% if column.id == article.column.id %} selected="selected" {% endif %}> {{ column }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- TAGS -->

                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text"
                           class="form-control col-3"
                           id="tags"
                           name="tags"

                           value={{ tags }}
                    >

                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
                <!-- GET -->
{#            {% else %}#}
{#            <form method="post" action="." enctype="multipart/form-data">#}
{#                <!-- Django中需要POST数据的地方都必须有csrf_token -->#}
{#                {% csrf_token %}#}
{#                <!-- 文章标题 -->#}
{#                <div class="form-group">#}
{#                    <!-- 标签 -->#}
{#                    <label for="title">文章标题</label>#}
{#                    <!-- 文本框 -->#}
{#                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">#}
{#                </div>#}
{##}
{#                <div class="form-group">#}
{#                    <label for="avatar">标题图</label>#}
{#                    <input type="file" class="form-control-file" name="avatar" id="avatar">#}
{#                </div>#}
{#                <!--column-->#}
{#                <div class="form-group">#}
{#                    <label for="column">栏目</label>#}
{#                    <select class="form-control"#}
{#                            id="column"#}
{#                            name="column"#}
{#                    >#}
{#                            <option value="none">请选择栏目..</option>#}
{#                        {% for column in columns %}#}
{#                            <option value="{{ column.id }}">{{ column }}</option>#}
{#                        {% endfor %}#}
{#                    </select>#}
{#                </div>#}
{##}
{#                <!-- TAGS -->#}
{##}
{#                <div class="form-group">#}
{#                    <label for="tags">标签</label>#}
{#                    <input type="text"#}
{#                           class="form-control col-3"#}
{#                           id="tags"#}
{#                           name="tags"#}
{##}
{#                           value={{ article.tags }}#}
{#                    >#}
{##}
{#                </div>#}
{#                <!-- 文章正文 -->#}
{#                <div class="form-group">#}
{#                    <label for="body">文章正文</label>#}
{#                    <!-- 文本区域 -->#}
{#                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>#}
{#                </div>#}
{#                <!-- 提交按钮 -->#}
{#                <button type="submit" class="btn btn-primary">完成</button>#}
{#            </form>#}
{#            {% endif %}#}
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% extends "base.html" %}
        {% load staticfiles %}

        {% block title %}
        文章详情
        {% endblock title %}

        {% block content %}
            <div class="container">

                <div class="row">
                    <div class="col-3 col-lg-2 card d-none d-md-block ">

                    </div>

                    <!-- 标题及作者 -->
                    <div class = "col-lg-8 col-md-9">
                        <h1 class="mt-4 mb-4">{{ article.title }}</h1>
                        <div class="alert alert-success">
                            <a  >作者：{{ article.author }}</a>
                            <!-- 加入本人登陆逻辑 -->
                            {% if user == article.author %}
                            <a href="#" onclick="confirm_delete()">   删除文章   </a>
                            <a href="/article/article-update/{{ article.id }}" >  修改文章   </a>
                            {% else %}
    {#                            <span class="operate" >删除文章</span>#}
    {#                            <span class="operate" >修改文章</span>#}

                            {% endif %}
                        </div>

                        <span>
                            <small class="col align-self-end" style="color: gray;">
                                浏览: {{ article.total_views }}
                            </small>
                        </span>

                            <!-- 文章正文 -->
                        <div class="row">
                            <div class="col-9">
                                <p>{{ article.body | safe }}</p>
                            </div>



                        </div>
                            {% if user.is_authenticated %}
                            <div>
                                <form
                                    action="{% url 'comment:post_comment' article.id %}"
                                    method="POST"
                                >
                                {% csrf_token %}
                                    <div class="form-group">
                                        <label for="body">
                                            <strong>
                                                我也要发言：
                                            </strong>
                                        </label>
        {#                                <textarea#}
        {#                                    type="text"#}
        {#                                    class="form-control"#}
        {#                                    id="body"#}
        {#                                    name="body"#}
        {#                                    rows="2"></textarea>#}
                                        <div>
                                            {{ comment_form.media }}
                                            {{ comment_form.body }}
                                        </div>
                                    </div>
                                    <!-- 提交按钮 -->
                                    <button type="submit" class="btn btn-primary ">发送</button>
                                </form>
                            </div>
                            <br>
                        {% else %}
                            <br>
                            <h5 class="row justify-content-center">
                                请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                            </h5>
                            <br>
                        {% endif %}




                        {% if comments.count %}
                            <h4>共有{{ comments.count }}条评论</h4>
                            <div>
                                {% for comment in comments %}
                                    <hr>
                                    <p>
                                        <strong style="color: pink">
                                            {{ comment.user }}
                                        </strong> 于
                                        <span style="color: green">
                                            {{ comment.created|date:"Y-m-d H:i:s" }}
                                        </span> 时说：
                                    </p>
                                    <pre style="font-family: inherit; font-size: 1em;">
                                        </pre>
                                    <div>
                                    {{ comment.body |safe }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% else %}
                            <h4>暂无评论，快来评论吧！</h4>
                        {% endif %}


                    </div>

                    <div class="col-2 card d-none d-lg-block collapse">
{#                        <div class="col-3 ">#}
                            <h4><strong>目录啊</strong></h4>
                            <hr>
                            <div>
                                {{ toc|safe }}
                            </div>
{#                        </div>#}

                     </div>




                </div>




                <script>
                    <!-- 弹窗逻辑 -->
                    function confirm_delete(){
                    layer.confirm('确定要删除吗？', {
                      btn: ['不了','删除'] //按钮
                    }, function(){
                      layer.msg('取消删除', {icon: 2});
                    }, function(){
                        location.href="/article/article-delete/{{ article.id }}"
                        layer.msg('删除成功', {icon: 1});

                    });
                 }

                </script>
            </div >


        {% endblock content %}
        {% block script %}
            <script>
                $(".django-ckeditor-widget").removeAttr('style');
            </script>


        {% endblock script %}


        <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'prism/prism.css' %}">

    </title>
</head>
<body>

</body>

</html>
{#/Users/aria/PycharmProjects/DjangoProject/venv/lib/python3.6/site-packages/ckeditor/static/ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.css#}